### ISSUE TITLE
[Errno 28] No space left on device: '~/.cache/huggingface/hub/models--lemonaddie--geowizard' even tho there is plenty of space

### ISSUE THREAD

**Issue by jurassicjordan** [kijai/ComfyUI-Geowizard#10]
# ComfyUI Error Report
## Error Details
- **Node Type:** geowizard_model_loader
- **Exception Type:** OSError
- **Exception Message:** [Errno 28] No space left on device: '/home/jordancruz/.cache/huggingface/hub/models--lemonaddie--geowizard'
## Stack Trace
```
  File "/home/jordancruz/Tools/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/home/jordancruz/Tools/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/home/jordancruz/Tools/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/home/jordancruz/Tools/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/home/jordancruz/Tools/ComfyUI/custom_nodes/ComfyUI-Geowizard/nodes.py", line 92, in loadmodel
    snapshot_download(repo_id="lemonaddie/geowizard", ignore_patterns=["*vae*", "*.ckpt", "*.pt", "*.png", "*non_ema*", "*safety_checker*", "*.bin"],

  File "/home/jordancruz/anaconda3/envs/comfyui/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)

  File "/home/jordancruz/anaconda3/envs/comfyui/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 265, in snapshot_download
    os.makedirs(os.path.dirname(ref_path), exist_ok=True)

  File "/home/jordancruz/anaconda3/envs/comfyui/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)

  File "/home/jordancruz/anaconda3/envs/comfyui/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)

```
## System Information
- **ComfyUI Version:** v0.2.2-50-g0bfc7cc
- **Arguments:** main.py --lowvram
- **OS:** posix
- **Python Version:** 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12510560256
  - **VRAM Free:** 7474380800
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-09-21 22:54:11,089 - root - INFO - Total VRAM 11931 MB, total RAM 31960 MB
2024-09-21 22:54:11,090 - root - INFO - pytorch version: 2.4.1+cu121
2024-09-21 22:54:12,136 - root - INFO - xformers version: 0.0.28.post1
2024-09-21 22:54:12,136 - root - INFO - Set vram state to: LOW_VRAM
2024-09-21 22:54:12,136 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-09-21 22:54:12,389 - root - INFO - Using xformers cross attention
2024-09-21 22:54:13,053 - root - INFO - [Prompt Server] web root: /home/jordancruz/Tools/ComfyUI/web
2024-09-21 22:54:13,373 - root - WARNING - Traceback (most recent call last):
  File "/home/jordancruz/Tools/ComfyUI/nodes.py", line 1994, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jordancruz/Tools/ComfyUI/custom_nodes/ComfyUI-3D-Pack/__init__.py", line 4, in <module>
    from pyhocon import ConfigFactory
ModuleNotFoundError: No module named 'pyhocon'

2024-09-21 22:54:13,373 - root - WARNING - Cannot import /home/jordancruz/Tools/ComfyUI/custom_nodes/ComfyUI-3D-Pack module for custom nodes: No module named 'pyhocon'
2024-09-21 22:54:15,233 - root - INFO - Total VRAM 11931 MB, total RAM 31960 MB
2024-09-21 22:54:15,233 - root - INFO - pytorch version: 2.4.1+cu121
2024-09-21 22:54:15,233 - root - INFO - xformers version: 0.0.28.post1
2024-09-21 22:54:15,233 - root - INFO - Set vram state to: LOW_VRAM
2024-09-21 22:54:15,234 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-09-21 22:54:15,246 - root - INFO - 
Import times for custom nodes:
2024-09-21 22:54:15,246 - root - INFO -    0.0 seconds: /home/jordancruz/Tools/ComfyUI/custom_nodes/websocket_image_save.py
2024-09-21 22:54:15,246 - root - INFO -    0.0 seconds (IMPORT FAILED): /home/jordancruz/Tools/ComfyUI/custom_nodes/ComfyUI-3D-Pack
2024-09-21 22:54:15,246 - root - INFO -    0.0 seconds: /home/jordancruz/Tools/ComfyUI/custom_nodes/ComfyUI_JPS-Nodes
2024-09-21 22:54:15,246 - root - INFO -    0.0 seconds: /home/jordancruz/Tools/ComfyUI/custom_nodes/ComfyUI_NYJY
2024-09-21 22:54:15,246 - root - INFO -    0.0 seconds: /home/jordancruz/Tools/ComfyUI/custom_nodes/ComfyUI-ToSVG
2024-09-21 22:54:15,246 - root - INFO -    0.0 seconds: /home/jordancruz/Tools/ComfyUI/custom_nodes/ComfyUI-GGUF
2024-09-21 22:54:15,246 - root - INFO -    0.0 seconds: /home/jordancruz/Tools/ComfyUI/custom_nodes/Comfyui_CXH_joy_caption
2024-09-21 22:54:15,246 - root - INFO -    0.0 seconds: /home/jordancruz/Tools/ComfyUI/custom_nodes/ComfyUI-Manager
2024-09-21 22:54:15,246 - root - INFO -    0.0 seconds: /home/jordancruz/Tools/ComfyUI/custom_nodes/comfy-image-saver
2024-09-21 22:54:15,246 - root - INFO -    0.0 seconds: /home/jordancruz/Tools/ComfyUI/custom_nodes/ComfyUI-Geowizard
2024-09-21 22:54:15,246 - root - INFO -    0.1 seconds: /home/jordancruz/Tools/ComfyUI/custom_nodes/ComfyUI_bitsandbytes_NF4
2024-09-21 22:54:15,246 - root - INFO -    0.1 seconds: /home/jordancruz/Tools/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
2024-09-21 22:54:15,246 - root - INFO -    0.2 seconds: /home/jordancruz/Tools/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
2024-09-21 22:54:15,247 - root - INFO -    0.4 seconds: /home/jordancruz/Tools/ComfyUI/custom_nodes/CogVideoX-Fun
2024-09-21 22:54:15,247 - root - INFO -    0.9 seconds: /home/jordancruz/Tools/ComfyUI/custom_nodes/was-node-suite-comfyui
2024-09-21 22:54:15,247 - root - INFO - 
2024-09-21 22:54:15,251 - root - INFO - Starting server

2024-09-21 22:54:15,251 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-21 23:03:16,631 - root - INFO - got prompt
2024-09-21 23:03:21,774 - root - INFO - Using xformers attention in VAE
2024-09-21 23:03:21,777 - root - INFO - Using xformers attention in VAE
2024-09-21 23:03:22,652 - root - ERROR - !!! Exception during processing !!! [Errno 28] No space left on device: '/home/jordancruz/.cache/huggingface/hub/models--lemonaddie--geowizard'
2024-09-21 23:03:22,653 - root - ERROR - Traceback (most recent call last):
  File "/home/jordancruz/Tools/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/jordancruz/Tools/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/jordancruz/Tools/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/jordancruz/Tools/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/jordancruz/Tools/ComfyUI/custom_nodes/ComfyUI-Geowizard/nodes.py", line 92, in loadmodel
    snapshot_download(repo_id="lemonaddie/geowizard", ignore_patterns=["*vae*", "*.ckpt", "*.pt", "*.png", "*non_ema*", "*safety_checker*", "*.bin"],
  File "/home/jordancruz/anaconda3/envs/comfyui/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/jordancruz/anaconda3/envs/comfyui/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 265, in snapshot_download
    os.makedirs(os.path.dirname(ref_path), exist_ok=True)
  File "/home/jordancruz/anaconda3/envs/comfyui/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/jordancruz/anaconda3/envs/comfyui/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: '/home/jordancruz/.cache/huggingface/hub/models--lemonaddie--geowizard'

2024-09-21 23:03:22,653 - root - INFO - Prompt executed in 6.02 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":9,"last_link_id":8,"nodes":[{"id":2,"type":"Image Resize","pos":{"0":623,"1":253},"size":{"0":315,"1":178},"flags":{},"order":4,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":1}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[4],"shape":3,"slot_index":0}],"properties":{"Node name for S&R":"Image Resize"},"widgets_values":["rescale","true","bilinear",0.01,512,512]},{"id":4,"type":"geowizard_model_loader","pos":{"0":635,"1":142},"size":{"0":315,"1":58},"flags":{},"order":3,"mode":0,"inputs":[{"name":"vae","type":"VAE","link":3}],"outputs":[{"name":"geowizard_model","type":"GEOWIZMODEL","links":[2],"shape":3,"slot_index":0}],"properties":{"Node name for S&R":"geowizard_model_loader"},"widgets_values":["fp16"]},{"id":5,"type":"VAELoader","pos":{"0":622,"1":36},"size":{"0":315,"1":58},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[3],"shape":3,"slot_index":0}],"properties":{"Node name for S&R":"VAELoader"},"widgets_values":["vae-ft-mse-840000-ema-pruned.ckpt"]},{"id":3,"type":"geowizard_sampler","pos":{"0":997,"1":198},"size":{"0":315,"1":222},"flags":{},"order":5,"mode":0,"inputs":[{"name":"geowizard_model","type":"GEOWIZMODEL","link":2},{"name":"image","type":"IMAGE","link":4}],"outputs":[{"name":"depth","type":"IMAGE","links":null,"shape":3,"slot_index":0},{"name":"normal","type":"IMAGE","links":[7],"shape":3,"slot_index":1}],"properties":{"Node name for S&R":"geowizard_sampler"},"widgets_values":[10,3,628095879400912,"randomize","indoor","DDIMScheduler",true]},{"id":8,"type":"UpscaleModelLoader","pos":{"0":1000,"1":10},"size":{"0":315,"1":58},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"UPSCALE_MODEL","type":"UPSCALE_MODEL","links":[6],"shape":3,"slot_index":0}],"properties":{"Node name for S&R":"UpscaleModelLoader"},"widgets_values":["RealESRGAN_x4plus.pth"]},{"id":9,"type":"ImageUpscaleWithModel","pos":{"0":990,"1":110},"size":{"0":340.20001220703125,"1":46},"flags":{},"order":6,"mode":0,"inputs":[{"name":"upscale_model","type":"UPSCALE_MODEL","link":6},{"name":"image","type":"IMAGE","link":7}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[8],"shape":3,"slot_index":0}],"properties":{"Node name for S&R":"ImageUpscaleWithModel"}},{"id":6,"type":"PreviewImage","pos":{"0":1367,"1":23},"size":[477.79243258346787,480.77615210709655],"flags":{},"order":7,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":8}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"}},{"id":1,"type":"LoadImage","pos":{"0":269,"1":40},"size":[315,314],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[1],"shape":3,"slot_index":0},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["meanddad.png","image"]}],"links":[[1,1,0,2,0,"IMAGE"],[2,4,0,3,0,"GEOWIZMODEL"],[3,5,0,4,0,"VAE"],[4,2,0,3,1,"IMAGE"],[6,8,0,9,0,"UPSCALE_MODEL"],[7,3,1,9,1,"IMAGE"],[8,9,0,6,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.6830134553650705,"offset":[-55.5413325834671,404.19124789290385]}},"version":0.4}

**Comment by jurassicjordan** [comment]
my mistake, I had a symlink to another drive that was full in cache, closing issue
